name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe any alternative approaches
    validations:
      required: false
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Parser improvements
        - Analysis algorithms
        - Visualization enhancements
        - CLI interface
        - Python API
        - Configuration system
        - Performance optimization
        - Documentation
        - Testing
        - Other
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Critical for my use case
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        I work with [type of Fortran code] and need this feature to [accomplish goal]
        This would help me by [specific benefit]
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If possible, provide an example of how you'd like to use this feature
      placeholder: |
        # Example command or code
        fortran-analyzer analyze my_project --new-feature-option
        
        # Or Python API usage
        analyzer.new_feature_method()
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false